name: run cucumber tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
     
    - name: Build with Maven
      run: mvn clean verify
       
    - name: Test Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
          name: Serenity Report               # Name of the folder
          path: target/cucumber-report/           # Path to test results
    
    - name: Cucumber Report
      uses: deblockt/cucumber-report-annotations-action@v1.11
      with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "target/cucumber-report/cucumber-report.json"   
          
    - name: Report
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
          branch: main
          folder: ./target/cucumber-report

    #~ - name: GH Pages
      #~ uses: JamesIves/github-pages-deploy-action@v4.4.1
      #~ with:
          #~ branch: gh_pages
          #~ folder: ./target/cucumber-report/          
     
